name:                Probs21to30
version:             0.1.0.0
github:              "nail82/Probs21to30"
license:             BSD3
author:              "Ted Satcher"
maintainer:          "ted.satcher@gmail.com"
copyright:           "BSD3"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nail82/Probs21to30#readme>

dependencies:
- base >= 4.7 && < 5
- directory
- bytestring
- trifecta >= 2
- raw-strings-qq
- containers
- vector >= 0.12

library:
  source-dirs: src

executables:
  Probs21to30-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Probs21to30
    when:
    - condition: false
      other-modules: Paths_Probs21to30

tests:
  Probs21to30-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Probs21to30
